version: '3'

services:
    myDB:
        image: postgres:15.3
        container_name: critio-db
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB= critio-db
        volumes:
            - ./postgres:/var/lib/postgresql/data
